### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined

### ISSUE THREAD

**Issue by robinscholz** [nuxt/module-builder#136]
When trying to use this package from within a built script instead of as a CLI, I am running into the following error. Any chance the correct exports could be added to the `package.json` ?

Use case is a monorepo that exports a bunch of vue helper functions, but also offers a nuxt module to install them. Instead of running the build script from the CLI, we would like to run it as part of a build script.

**Comment by danielroe** [comment]
Would you provide an example of the code you're using that isn't working - and what you're trying to import? (If the issue is `prepareModule`, I've just exposed that in 76b56549f7a71c3ce9ec19aab3accbd34703d2c9.)

I suspect the issue is that you are running in a CJS context, and this tool is ESM-only (`type: module`).

**Comment by robinscholz** [comment]
@danielroe I just stumbled upon this issue again and can’t recall how I ran into this.  Sorry for never getting back to you. Will close the issue!
