### ISSUE TITLE
Plugin injections are unknown

### ISSUE THREAD

**Issue by ibockowsky** [nuxt/module-builder#215]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nlraem?file=app.vue

### Describe the bug

![image](https://github.com/nuxt/nuxt/assets/22965136/f4f0797c-cf35-4703-ba15-19b1f25fdc1c)

This type should be known

**Comment by TheAlexLichter** [comment]
Related: https://github.com/nuxt/nuxt/issues/24885
Possibly related: unjs/mkdist#22

In this issue, we should find the root cause why the generated plugin types are any though 🤔
<img width="708" alt="image" src="https://github.com/nuxt/nuxt/assets/640208/f58124f9-5a99-4373-9fc6-8f617162a03b">

Moving this to the module builder repo.

**Comment by TheAlexLichter** [comment]
~~But I wonder - apparently this is correct by design? 🤔~~
https://github.com/nuxt/module-builder/blob/f158ffaf6443909c3882337ebda49de4a8db2d4f/test/build.spec.ts#L87-L94

https://github.com/nuxt/module-builder/blob/f158ffaf6443909c3882337ebda49de4a8db2d4f/example/src/runtime/plugin.ts#L1

**Comment by RyanClementsHax** [comment]
If it helps, I was able to reproduce this with a custom plugin too https://codesandbox.io/p/devbox/nuxt-plugin-typing-repro-xvtm2t

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/module-builder/pull/255.
