### ISSUE TITLE
provide option to copy along static files

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/module-builder#63]
Sometimes you want to copy static files (in my case a ts file that servers as the source for `addTemplate`). This currently doesn't seem to be possible.

**Comment by pi0** [comment]
Does it works if you put it inside `src/runtime/static`?

**Comment by harlan-zw** [comment]
Doing this worked for me

```ts
nuxt.hooks.hook('nitro:config', (nitroConfig) => {
  nitroConfig.publicAssets = nitroConfig.publicAssets || []
  nitroConfig.publicAssets.push({ dir: resolve('./runtime/public'), maxAge: 31536000 })
})
```

**Comment by pi0** [comment]
@harlan-zw Nice. That would be a nice kit utility candidate.

**Comment by IlyaSemenov** [comment]
@pi0:

> Does it works if you put it inside `src/runtime/static`?

Not really. `template.ts` is copied but it's transformed into the pair of `.mjs` and `.d.ts` which is not desireable (in particular, that means `addTemplate` calls should be different between dev and production).

One could work around that by using non-ts extension (such as `.ts.template`) but then:
* The file is not recognized by IDE (unless manually fiddled).
* `addTemplate` needs explicit `dst`, otherwise it keeps the `.template` extension. But explicit `dst` means the `filename.[hash].ts` mechanism is not used.

All and all, that's not really an option. We need a way to copy over certain files verbatim.

Suggestions:
- Treat `.template.ts` as an exception for transformation.
- Copy the entire `src/assets` into `dist/assets` (then it's up to the developer how to use it).

**Comment by pi0** [comment]
I think you still can use a top level directory and include it in package.json files without transforms (dist and src having same relative path) but sure supporting an `assets` type could be nice option. 

Upstream: https://github.com/unjs/unbuild/issues/266

**Comment by danielroe** [comment]
There is a new `copy` builder in `unbuild` v3, which will be included in the upcoming v1 release of module-builder.
