### ISSUE TITLE
SCSS files get renamed with *.mjs extension

### ISSUE THREAD

**Issue by andrucado** [nuxt/module-builder#67]
Hi!

Just updated the nuxt-module-builder to the latest from rc-13, noticed that my *.scss files inside the runtime folder are being renamed to *.mjs in the dist build.

**Comment by kkz6** [comment]
I have also faced the same issue and when I was using the package it is getting file "Failed to resolve *.mjs issue"

**Comment by dwightjack** [comment]
I think this is an issue with `mkdist` (which is the build tool used internally by this package). If I understand correctly this package forces every file inside the `runtime` folder to have `.mjs` extension ([source](https://github.com/nuxt/module-builder/blob/main/src/build.ts#L25)), then the sass loader in mkdist uses the `mjs` extension instead of the correct one ([source](https://github.com/unjs/mkdist/blob/main/src/loaders/sass.ts#L17)).

I am not sure of how to fix this issue though 🤔 . Clearly, this tool is not yet ready to be used for non-trivial modules. It's probably better to use https://github.com/unjs/unbuild directly or a combination of rollup + esbuild.
